CREATE TABLE "PurchaseRequest" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "organizationName" TEXT NOT NULL,
  "projectName" TEXT,
  "applicantName" TEXT NOT NULL,
  "requestedAt" TIMESTAMP(3) NOT NULL,
  "supplierName" TEXT NOT NULL,
  "purchaseType" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "specification" TEXT NOT NULL,
  "quantity" DECIMAL(18,2) NOT NULL,
  "unit" TEXT NOT NULL,
  "unitPrice" DECIMAL(18,2) NOT NULL,
  "currency" "CurrencyCode" NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "purpose" TEXT NOT NULL,
  "expectedArrivalDate" TIMESTAMP(3) NOT NULL,
  "requiresPayment" BOOLEAN NOT NULL DEFAULT true,
  "requiresInventory" BOOLEAN NOT NULL DEFAULT true,
  "linkedContractName" TEXT,
  "status" TEXT NOT NULL,
  "currentApprovalNode" TEXT,
  "currentHandler" TEXT,
  "approvalHistory" JSONB NOT NULL,
  "attachments" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PurchaseRequest_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PurchaseLedger" (
  "id" TEXT NOT NULL,
  "purchaseRequestId" TEXT NOT NULL,
  "organizationName" TEXT NOT NULL,
  "supplierName" TEXT NOT NULL,
  "purchaseType" TEXT NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "currency" "CurrencyCode" NOT NULL,
  "createdAtDate" TIMESTAMP(3) NOT NULL,
  "status" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PurchaseLedger_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ContractApproval" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "organizationName" TEXT NOT NULL,
  "projectName" TEXT,
  "applicantName" TEXT NOT NULL,
  "requestedAt" TIMESTAMP(3) NOT NULL,
  "contractName" TEXT NOT NULL,
  "contractNo" TEXT NOT NULL,
  "contractType" TEXT NOT NULL,
  "counterpartyName" TEXT NOT NULL,
  "currency" "CurrencyCode" NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "signedAt" TIMESTAMP(3) NOT NULL,
  "effectiveDate" TIMESTAMP(3) NOT NULL,
  "expiryDate" TIMESTAMP(3) NOT NULL,
  "paymentTerms" TEXT NOT NULL,
  "settlementMethod" TEXT NOT NULL,
  "summary" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "currentApprovalNode" TEXT,
  "currentHandler" TEXT,
  "ocrStatus" TEXT NOT NULL,
  "approvalHistory" JSONB NOT NULL,
  "attachments" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ContractApproval_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ContractLedger" (
  "id" TEXT NOT NULL,
  "contractRequestId" TEXT NOT NULL,
  "organizationName" TEXT NOT NULL,
  "contractName" TEXT NOT NULL,
  "contractNo" TEXT NOT NULL,
  "counterpartyName" TEXT NOT NULL,
  "amount" DECIMAL(18,2) NOT NULL,
  "currency" "CurrencyCode" NOT NULL,
  "effectiveDate" TIMESTAMP(3) NOT NULL,
  "expiryDate" TIMESTAMP(3) NOT NULL,
  "status" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ContractLedger_pkey" PRIMARY KEY ("id")
);
